### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Zaku212** [BSData/Firestorm-Armada-v2#59]
Hi all,

I am Zaku212 from the Firestorm Armada forums and FB group. I heard you guys are having less time than usual to update this, so I was wondering if I could be of assistance?

Regards

Isaac

**Comment by amis92** [comment]
Well, I can't lie, we direly need any help available. Please accept the invitation and sacrifice your lifetime in service of greater god of datafiles. ;) Welcome aboard.
