### ISSUE TITLE
[Anon] Bug report: Rense_System_Navy_Fleet.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Firestorm-Armada-v2#65]
**File:** Rense_System_Navy_Fleet.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** I'm looking at the Zenian League book and at the downloadable RSN PDF and I do not see any way that  a Cruiser Squadron can bring an escort Heavy Cruiser or that a Heavy Cruiser Squadron can bring Cruisers as accompanyment.

**Comment by danimrath** [comment]
Very odd! They used to be able to :).

**Comment by efalsken** [comment]
The question was answered online. It's in the core rulebook that you can upgrade one cruiser to a heavy in a cruiser squadron.
