### ISSUE TITLE
[Anon] Bug report: Oroshan_Fleet.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Firestorm-Armada-v2#67]
**File:** Oroshan_Fleet.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** If i select an Oroshon fleet without setting a point limit it does not show the dreadnought as a choice selection for T1

**Comment by danimrath** [comment]
What would you suggest I set the limit of dreadnoughts to if there is no point limit? There are none allowed at less than 800.

**Comment by steve990** [comment]
The points limit must be set at the appropriate level for the dreadnought to show as an option. Closing issue.
