### ISSUE TITLE
Update Fleets with April2016 ship stats and taskforce ships

### ISSUE THREAD

**Issue by efalsken** [BSData/Firestorm-Armada-v2#70]
The fleet guides here have some changes here and there to the old ships, but also include the stats for all of the System Wars and Taskforce ships: http://www.spartangames.co.uk/resources/downloads

**Comment by steve990** [comment]
We are working on these, and are discussing a reorganization of the files. Will update as soon as we can! :)

**Comment by efalsken** [comment]
Let me know if I can help. Now that I've finished with the Eldar codex updates, I'm free again.

**Comment by steve990** [comment]
All done now - sorry for the delay. Was a HUGE rewrite! :)
