### ISSUE TITLE
Move the ship name to the end of profile names.

### ISSUE THREAD

**Issue by efalsken** [BSData/Firestorm-Armada-v2#71]
I find it much easier to read the ship weapon and stat profiles by ship class:

> Battleship (Nausicaa) - Fore Fixed         Kinetic
> Battleship (Nausicaa) - Fore Fixed         Torpedo
> Battleship (Nausicaa) - Gun Rack           Primary
> Escort (Buckler) - Gun Rack                   Primary

is easier to read than the current

> Conqueror/Nausicaa D Fore (Fixed)         Kinetic
> Conqueror/Nausicaa D Gun Rack             Primary
> Conqueror/Nausicaa I Fore (Fixed)         Torpedo
> Buckler/Retarius - Gun Rack                    Primary

I know that the `D` and `I` are supposed to be Direct and Indirect, but is the Name of the weapon really the correct place for it?

What about moving the Direct/Indirect indicator and the weapon's arc to its own profile column?

**Comment by steve990** [comment]
This has been totally rewritten and now has a separate field for each aspect of a weapon like arc, category and MARs.
